version: '3.4'
services:
  project:
    image: lorayzm/server:latest
    depends_on:
      - db
    ports:
      - 7000:80
      - 3000:3000
      - 3001:3001
    volumes:
      - ./project:/srv/app
    environment:
      NODE_ENV: development
  db:
    image: mariadb
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_ROOT_PASSWORD: secret
volumes:
  db: